version: '3.1'

services:
  postgre:
    image: postgres
    environment:
      POSTGRES_PASSWORD: psqlpass
      POSTGRES_USER: postgres
    ports:
      - 29345:5432
    volumes: 
      - ./dbdata:/var/lib/postgresql/data